Feature/be/review/002/review create
codestates-seb/seb41_main_021 pull request #188
Opened 2023-01-21 09:46 UTC by Chaeeunm

## 작업 내용 (Content)
review create 기능 수정/보완
review create test/docs

## 기타 사항 (Etc)
운전자 - 탑승자 확인
한 사람이 같은 야타 글+같은 대상자 에 대해 두번 글 쓸 수 없게
해당 yataMember가 도착완료(=결제완료) 상태가 아닐 시 글 쓸 수 없게

## Merge 전 필요 작업 (Checklist before merge)
- [ ] 예) XX 테이블 추가, 앱 배포 등
- [ ] eg) Create XX table, Deploy app etc

## Merge 후 필요 작업 (Checklist after merge)
- PR이 생성되면 코드 리뷰 요청한 개발자에게 슬랙으로 알려주세요.

2023-01-21 09:54 UTC, gudcks0305 requested changes
조금 더 수정~

2023-01-21 09:54 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/review/dto/ReviewDto.java
> +        private String fromMemberEmail;
리스폰스는 이메일이 아니라 닉네임이 좋지 않을까요~

2023-01-21 09:54 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/review/dto/ReviewDto.java
> +        private String toMemberEmail;
동일

2023-01-21 09:54 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/review/service/ReviewServiceImpl.java
> +        }
여기 쪼꼼 뭔가 이상한데 제대로 볼게요

2023-01-21 09:54 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/review/service/ReviewServiceImpl.java
> +        if(optionalReview.isPresent()) throw new CustomLogicException(ExceptionCode.ALREADY_REVIEWED);
여긴 stream 하나로 묶어 처리하는게 좋을거같아요

2023-01-21 09:54 UTC, gudcks0305 commented on backend/src/test/java/com/yata/backend/domain/review/factory/ReviewFactoty.java
> +        checklistIds.add(2L);
for 문을 쓰든 랜덤 값을 넣든...

2023-01-21 09:59 UTC, Chaeeunm commented on backend/src/main/java/com/yata/backend/domain/review/dto/ReviewDto.java
> +        private String fromMemberEmail;
그러네요 수정할게요!

2023-01-22 09:43 UTC, Joo614 approved these changes
goooooood

2023-01-22 09:43 UTC, gudcks0305 approved these changes

2023-01-22 09:44 UTC, merged