Feature/be/yata/001
codestates-seb/seb41_main_021 pull request #63
Opened 2023-01-10 14:46 UTC by Chaeeunm

## 작업 내용 (Content)
1. yata 에 출발시간 /도착시간 추가
2. 너타생성 /나타생성 로직 하나로 합치고, api url은 쿼리 파라미터로 구분

## 기타 사항 (Etc)
date타입으로 받는거 에러가 계속 나서 todo로 남겨두었습니다

2023-01-10 15:12 UTC, gudcks0305 requested changes

2023-01-10 15:12 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/yata/entity/Yata.java
> +    private String timeOfArrival;
이건 제가 내일 봐드릴게요...

2023-01-10 15:12 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/yata/service/YataServiceImpl.java
> +        else if(yataStatus.equals("nata")){yata.setYataStatus(Yata.YataStatus.YATA_NATA);}
이건 switch case 로 하는게 깔끔해요 저희 java 17 써서 arrow func 쓸 수 있거든요?
enhanced switch Case 고고

그리고 if else if 로 하면 이상하게 들어오면 어떻게 하실 거져...? 
제가 알기론 Neota nata enum 으로 들어가있는게 있던거 같은데 그걸로 하심이 좋지 않을까

2023-01-10 15:14 UTC, Joo614 commented on backend/src/main/java/com/yata/backend/domain/yata/controller/YataController.java
> +    @PostMapping
api 주소에 쿼리 파라미터를 넣으면 @PostMapping() 안에 "?yataStatus=~~" 이렇게 안넣어줘도 되는 건가욤??

2023-01-10 15:17 UTC, gudcks0305 commented on backend/src/main/java/com/yata/backend/domain/yata/controller/YataController.java
> +    @PostMapping
https://javanitto.tistory.com/43 요렇게 넣긴 해야져 ㅎㅎ

2023-01-10 15:20 UTC, Chaeeunm commented on backend/src/main/java/com/yata/backend/domain/yata/service/YataServiceImpl.java
> +        else if(yataStatus.equals("nata")){yata.setYataStatus(Yata.YataStatus.YATA_NATA);}
예외로직 추가하는것을 깜빡했네연,,
arrow func 검색해보게씀당

2023-01-10 15:23 UTC, Chaeeunm commented on backend/src/main/java/com/yata/backend/domain/yata/controller/YataController.java
> +    @PostMapping
> api 주소에 쿼리 파라미터를 넣으면 @PostMapping() 안에 "?yataStatus=~~" 이렇게 안넣어줘도 되는 건가욤??

저는 글케 알고있었는데 enum으로 받을수가 있네염

2023-01-11 07:24 UTC, Joo614 approved these changes
화긴 ~

2023-01-11 07:26 UTC, gudcks0305 approved these changes

2023-01-11 07:26 UTC, merged